#!/usr/bin/env bash
# =====================================================================
# FullStackAutoQuant — One-Command Remote Deploy & Run
# Usage:  ./scripts/deploy.sh <SSH_HOST> [--run] [--setup-only]
#
# Examples:
#   ./scripts/deploy.sh user@1.2.3.4                 # setup + run
#   ./scripts/deploy.sh MySSHAlias                   # uses ~/.ssh/config
#   ./scripts/deploy.sh user@host --setup-only       # only deploy, don't run
#   ./scripts/deploy.sh user@host --run              # run only (already deployed)
#
# Requirements:
#   - Local: bash, tar, scp, ssh
#   - Remote: Python 3.10+, ~500MB disk, internet (for pip install)
#   - .env file with TUSHARE token at project root
# =====================================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { printf "${CYAN}[deploy]${NC} %s\n" "$*"; }
ok()   { printf "${GREEN}[  OK  ]${NC} %s\n" "$*"; }
warn() { printf "${YELLOW}[ WARN ]${NC} %s\n" "$*"; }
die()  { printf "${RED}[FATAL]${NC} %s\n" "$*" >&2; exit 1; }

# ── Parse args ──────────────────────────────────────────────────────
SSH_HOST="${1:-}"
[[ -z "$SSH_HOST" ]] && die "Usage: $0 <SSH_HOST> [--run] [--setup-only]"
shift

MODE="full"  # full | setup-only | run-only
for arg in "$@"; do
  case "$arg" in
    --setup-only) MODE="setup-only" ;;
    --run)        MODE="run-only" ;;
    *) die "Unknown flag: $arg" ;;
  esac
done

# ── Resolve project root ───────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# ── Validate local files ───────────────────────────────────────────
[[ -f ".env" ]]                    || die ".env not found. Copy .env.example → .env and set TUSHARE token."
[[ -f "weights/norm_params.pkl" ]] || die "weights/norm_params.pkl not found."
[[ -f "pyproject.toml" ]]          || die "Not in project root? pyproject.toml missing."

TUSHARE_TOKEN="$(grep '^TUSHARE=' .env | cut -d= -f2)"
[[ -n "$TUSHARE_TOKEN" && "$TUSHARE_TOKEN" != "your_tushare_token_here" ]] \
  || die "TUSHARE token not set in .env"

# ── Remote paths ───────────────────────────────────────────────────
# Detect remote $HOME reliably (Lightning AI maps ~ differently)
REMOTE_HOME="$(ssh "$SSH_HOST" 'echo $HOME')"
REMOTE_DIR="${REMOTE_HOME}/FullStackAutoQuant"
log "Remote target: ${SSH_HOST}:${REMOTE_DIR}"

# ── Helper: run command on remote ──────────────────────────────────
remote() { ssh "$SSH_HOST" "$@"; }

# =====================================================================
# PHASE 1: Pack & Upload
# =====================================================================
do_setup() {
  log "Phase 1/3: Packing project..."
  local TARBALL="/tmp/fsaq_deploy_$$.tar.gz"
  # Exclude large runtime-generated files (*.h5 caches, *.parquet)
  # These are regenerated by the workflow; only source code + weights are needed.
  tar czf "$TARBALL" \
    --exclude='.git' --exclude='__pycache__' --exclude='.mypy_cache' \
    --exclude='.ruff_cache' --exclude='.pytest_cache' --exclude='*.egg-info' \
    --exclude='dist' --exclude='.DS_Store' --exclude='.agent' --exclude='.gemini' \
    --exclude='venv' --exclude='.venv' --exclude='output' --exclude='.coverage' \
    --exclude='*.h5' --exclude='*.parquet' \
    -C "$PROJECT_ROOT" .
  local SIZE
  SIZE="$(du -h "$TARBALL" | cut -f1)"
  ok "Packed: ${SIZE}"

  log "Phase 1/3: Uploading to ${SSH_HOST}..."
  remote "mkdir -p '${REMOTE_DIR}'"
  scp -q "$TARBALL" "${SSH_HOST}:${REMOTE_DIR}/_deploy.tar.gz"
  remote "cd '${REMOTE_DIR}' && tar xzf _deploy.tar.gz && rm _deploy.tar.gz"
  rm -f "$TARBALL"
  ok "Uploaded & extracted"

  # =====================================================================
  # PHASE 2: Setup environment
  # =====================================================================
  log "Phase 2/3: Setting up Python environment..."

  # Detect Python and install pip/venv if needed
  remote "
    set -e
    cd '${REMOTE_DIR}'

    # Find python3 (>= 3.10)
    PY=\$(command -v python3 2>/dev/null || true)
    if [ -z \"\$PY\" ]; then
      echo 'ERROR: python3 not found on remote server' >&2
      exit 1
    fi

    # Check version
    PY_VER=\$(\$PY -c 'import sys; print(f\"{sys.version_info.minor}\")')
    if [ \"\$PY_VER\" -lt 10 ]; then
      echo \"ERROR: Python 3.10+ required, found 3.\${PY_VER}\" >&2
      exit 1
    fi

    # Ensure pip & venv are available
    if ! \$PY -m pip --version >/dev/null 2>&1; then
      echo 'Installing pip...'
      if command -v apt-get >/dev/null 2>&1; then
        sudo apt-get update -qq && sudo apt-get install -y -qq python3-pip python3-venv 2>&1 | tail -3
      elif command -v yum >/dev/null 2>&1; then
        sudo yum install -y -q python3-pip python3-venv 2>&1 | tail -3
      elif command -v dnf >/dev/null 2>&1; then
        sudo dnf install -y -q python3-pip python3-devel 2>&1 | tail -3
      else
        \$PY -m ensurepip 2>/dev/null || { echo 'Cannot install pip automatically'; exit 1; }
      fi
    fi

    # Create venv if missing
    if [ ! -f .venv/bin/activate ]; then
      echo 'Creating virtualenv...'
      \$PY -m venv .venv
    fi

    # Install dependencies
    echo 'Installing dependencies (this may take a few minutes on first run)...'
    . .venv/bin/activate
    pip install --upgrade pip setuptools wheel -q
    pip install -e . -q 2>&1 | tail -5
    echo 'SETUP_COMPLETE'
  "
  ok "Environment ready"
}

# =====================================================================
# PHASE 3: Run workflow
# =====================================================================
do_run() {
  log "Phase 3/3: Running Lite Inference Workflow..."
  remote "
    set -e
    cd '${REMOTE_DIR}'
    . .venv/bin/activate
    export TUSHARE='${TUSHARE_TOKEN}'
    mkdir -p output
    bash scripts/run_lite_workflow.sh
  "
  ok "Workflow complete!"

  # Fetch result
  log "Downloading results..."
  mkdir -p "${PROJECT_ROOT}/output"
  scp -q "${SSH_HOST}:${REMOTE_DIR}/output/ranked_scores.csv" \
         "${PROJECT_ROOT}/output/ranked_scores_$(date +%F)_remote.csv" 2>/dev/null \
    && ok "Results saved: output/ranked_scores_$(date +%F)_remote.csv" \
    || warn "Could not download results (check remote output/ranked_scores.csv)"
}

# ── Execute ─────────────────────────────────────────────────────────
case "$MODE" in
  full)       do_setup; do_run ;;
  setup-only) do_setup; ok "Setup complete. Run with: $0 $SSH_HOST --run" ;;
  run-only)   do_run ;;
esac

echo ""
echo "───────────────────────────────────────────────────────────"
echo "  Re-run anytime:  $0 ${SSH_HOST} --run"
echo "  Full redeploy:   $0 ${SSH_HOST}"
echo "───────────────────────────────────────────────────────────"
