#!/usr/bin/env bash
# push_csv_to_repo.sh — Commit & push ranked_scores.csv to private GitHub repo
#
# The CSV is in .gitignore (output/ is excluded), so we use `git add -f`
# to force-track it. Each day creates a new commit with the date.
#
# Prerequisites:
#   - gh auth login (already done via schedule command sourcing .env)
#   - git remote "origin" points to the private repo
#
# Usage:
#   bash scripts/push_csv_to_repo.sh
set -euo pipefail

log(){ printf "[%s] %s\n" "$(date +'%F %T')" "$*"; }

# ── Resolve paths ──────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CSV_PATH="$PROJECT_ROOT/output/ranked_scores.csv"

cd "$PROJECT_ROOT"

# ── Validate ───────────────────────────────────────────────────
if [[ ! -f "$CSV_PATH" ]]; then
  log "ERROR: CSV not found: $CSV_PATH"
  exit 1
fi

# Ensure git is configured
if ! git remote get-url origin &>/dev/null; then
  log "ERROR: git remote 'origin' not configured"
  exit 1
fi

# Ensure gh credential helper is active
gh auth setup-git 2>/dev/null || true

# ── Determine data date from CSV content ──────────────────────
# Use the datetime column (row 1) as the canonical data date,
# not the system calendar date.  This prevents creating duplicate
# archives when the pipeline runs on non-trading days (weekends,
# holidays) — the data date stays the same as the last trading day.
DATA_DATE=$(awk -F',' 'NR==2 {print $1}' "$CSV_PATH")
if [[ -z "$DATA_DATE" ]]; then
  log "ERROR: Cannot extract data date from $CSV_PATH"
  exit 1
fi
log "Data date from CSV content: $DATA_DATE"

# ── Archive: keep date-stamped copy ───────────────────────────
ARCHIVE_DIR="$PROJECT_ROOT/output/history"
mkdir -p "$ARCHIVE_DIR"
ARCHIVE_FILE="$ARCHIVE_DIR/ranked_scores_${DATA_DATE}.csv"

if [[ -f "$ARCHIVE_FILE" ]]; then
  log "Archive already exists for data date ${DATA_DATE} — skipping (no new market data)"
  exit 0
fi

cp "$CSV_PATH" "$ARCHIVE_FILE"

# ── Git commit & push ─────────────────────────────────────────
# Force-add because output/ is in .gitignore
git add -f "$CSV_PATH"
git add -f "$ARCHIVE_FILE"

# Check if there are actual changes to commit
if git diff --cached --quiet; then
  log "No changes to commit (CSV unchanged)"
  exit 0
fi

git commit -m "Daily ranked scores ${DATA_DATE}

Auto-generated by run_inference.sh
Data date: ${DATA_DATE}
Stocks: $(tail -n +2 "$CSV_PATH" | wc -l) instruments

[skip ci]"

log "Pushing to origin/main ..."
git push origin main

log "CSV pushed to private repo!"
log "   View: https://github.com/Zizhao-HUANG/FullStackAutoQuant-private/blob/main/output/ranked_scores.csv"
log "   History: https://github.com/Zizhao-HUANG/FullStackAutoQuant-private/tree/main/output/history/"
