#!/usr/bin/env bash
# push_csv_to_repo.sh — Commit & push ranked_scores.csv to private GitHub repo
#
# The CSV is in .gitignore (output/ is excluded), so we use `git add -f`
# to force-track it. Each day creates a new commit with the date.
#
# Prerequisites:
#   - gh auth login (already done via schedule command sourcing .env)
#   - git remote "origin" points to the private repo
#
# Usage:
#   bash scripts/push_csv_to_repo.sh
set -euo pipefail

log(){ printf "[%s] %s\n" "$(date +'%F %T')" "$*"; }

# ── Resolve paths ──────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CSV_PATH="$PROJECT_ROOT/output/ranked_scores.csv"
TODAY=$(date +'%Y-%m-%d')

cd "$PROJECT_ROOT"

# ── Validate ───────────────────────────────────────────────────
if [[ ! -f "$CSV_PATH" ]]; then
  log "ERROR: CSV not found: $CSV_PATH"
  exit 1
fi

# Ensure git is configured
if ! git remote get-url origin &>/dev/null; then
  log "ERROR: git remote 'origin' not configured"
  exit 1
fi

# Ensure gh credential helper is active
gh auth setup-git 2>/dev/null || true

# ── Archive: keep date-stamped copy ───────────────────────────
ARCHIVE_DIR="$PROJECT_ROOT/output/history"
mkdir -p "$ARCHIVE_DIR"
cp "$CSV_PATH" "$ARCHIVE_DIR/ranked_scores_${TODAY}.csv"

# ── Git commit & push ─────────────────────────────────────────
# Force-add because output/ is in .gitignore
git add -f "$CSV_PATH"
git add -f "$ARCHIVE_DIR/ranked_scores_${TODAY}.csv"

# Check if there are actual changes to commit
if git diff --cached --quiet; then
  log "No changes to commit (CSV unchanged)"
  exit 0
fi

git commit -m "Daily ranked scores ${TODAY}

Auto-generated by run_lite_workflow.sh
Inference date: ${TODAY}
Stocks: $(tail -n +2 "$CSV_PATH" | wc -l) instruments

[skip ci]"

log "Pushing to origin/main ..."
git push origin main

log "CSV pushed to private repo!"
log "   View: https://github.com/Zizhao-HUANG/FullStackAutoQuant-private/blob/main/output/ranked_scores.csv"
log "   History: https://github.com/Zizhao-HUANG/FullStackAutoQuant-private/tree/main/output/history/"
